apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: kot9i0qcq-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:ab047e263a0155e6c8423a052fed4b7d300c4594@sha256:3fe4c0d4773c4c6317984d94fafbdb78aaf455d9b7ee1094e6a4d737c845194f
          name: container-image
